### ISSUE TITLE
QIP module extension and integration with other modules

### ISSUE THREAD

**Issue by nwlambert** [qutip/qutip#441]
The QIP module is a set of tools for simulating quantum computing, from the high-level of algorithms, down to individual qubit control sequences in a particular physical architecture. So far it has functions for common quantum information processing tasks, including pre-defined quantum gates, along with functions for applying arbitrary 1, 2, and 3 qubit gates to arbitrary target and control qubits in a register of N qubits, circuit representations, a library of quantum algorithms, and models for some common physical QIP architectures.

Our goal is to have a set of tools to analyse the influence of unexpected noise sources on a given algorithm realized on a particular architecture, as well as being used as an educational tool for teaching QIP concepts.  

QIP module enhancements we plan to implement include:
1. Simulation of stabilizer circuits and quantum error correction codes.
2. Simulation of common quantum algorithms - Shor's Factorization, Grover's Search, Quantum Teleportation, and more...( http://math.nist.gov/quantum/zoo/ )
3. Extend platform to simulate specific quantum computing architectures - Create models to simulate different experimental quantum computing setups like Xmons, including typical environmental noise sources, and limitations on control and readout associated with each example.
4. Combine the qip and qcontrol modules to optimize circuit and gate decomposition and find ideal fast control pulses to realize particular gates, given physically available limitations of a particular architecture. 
5. Platform for simulating quantum chemistry on a quantum computer - Create example codes for calculating the ground state of molecules, following specific examples found in DOI: 10.1126/science.1113479 and elsewhere.  
6. Combine the qip and HEOM/RC solvers to investigate the effect of a non-markovian and nonperturbative environment  on error correction and common algorithms.

**Comment by ajgpitch** [comment]
@sahmed95 Have you seen this? Looks like a brief

**Comment by sahmed95** [comment]
Thank you for tagging me here. I am trying to do something related to 4 now. Gate decomposition based on the ICM model for topological quantum computing. 

I could pursue some of these goals for my first thesis (Jul - Dec) next year. What do you think ?

**Comment by ajgpitch** [comment]
We (@nwlambert) wrote those objectives about a year ago. I can only assume
that they are still relevant.
But certainly I think some are too big to do an a part time basis.
Let's see what whoever ends up supervising you thinks about it :)

**Comment by nathanshammah** [comment]
I think this is still relevant and could be a topic of work for future google SoC students or other students. 

Recently I met Johannes Bausch who at Caltech used the algorithm toolbox for some fun example (predict the winner of the [world cup](https://quantumfrontiers.com/2018/07/02/the-world-cup-from-a-quantum-perspective/)), but this points to the fact that the QIP suite is still used. 

Also, there might be room for basic I/O functionality to QiSKit and Rigetti. This quantum compiler integrability would further drive interest from the educational point of view. QuTiP is the best playground to learn realistic quantum mechanics and the notion of a compiler back-end could prove enticing.

**Comment by nathanshammah** [comment]
Moving this to the wiki as a future project.

**Comment by ajgpitch** [comment]
I have just included part of this as a GSoC project on [our GSoC project wiki](https://github.com/qutip/qutip/wiki//Google-Summer-of-Code-2019).

The rest I think we should move to some kind of QIP module wishlist

**Comment by nathanshammah** [comment]
Some of these points have been addressed by #1065. The rest could become also a [project](https://github.com/qutip/qutip/projects
) and be added also to the wiki as available project.

**Comment by hodgestar** [comment]
@BoxiLi Should we migrate this issue across to qutip-qip?

**Comment by BoxiLi** [comment]
I think we can close it? Or maybe migrate it to the collection of ideas? Each of the points is quite a big project. Points 3 and 4 are partially addressed.

**Comment by hodgestar** [comment]
Let's close it.
